SCMOD-8516: disable tls 1.1 and 1.2
caf-archive/opensuse-java11-images pull request #9
Opened 2020-03-31 17:01 UTC by gaana-vishwnath

2020-03-31 17:42 UTC, dermot-hardy reviewed
You need to update the release notes. We need to get back into the practice of doing that. Apart from that this change looks OK. I see you have disabled further ciphers but have you confirmed that this is the complete list of ciphers that need to be disabled?

2020-04-01 08:50 UTC, gaana-vishwnath commented
> You need to update the release notes. We need to get back into the practice of doing that. Apart from that this change looks OK. I see you have disabled further ciphers but have you confirmed that this is the complete list of ciphers that need to be disabled?

Updated the release notes. I used the  https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility link to add the tlsv1.2 ciphers. But I am not sure if that is the complete list.

2020-04-01 08:54 UTC, michael-bryson commented
There is no update to the releases notes showing in here.

2020-04-01 09:59 UTC, michael-bryson commented on release-notes-2.1.0.md
> +- **SCMOD-8516**: Extend the TLS/SSL cipher hardening of the Java base images to disallow tlsv1, tlsv1.1 and tlsv1.2
tls should be uppercase

2020-04-01 10:04 UTC, gaana-vishwnath commented on release-notes-2.1.0.md
> +- **SCMOD-8516**: Extend the TLS/SSL cipher hardening of the Java base images to disallow tlsv1, tlsv1.1 and tlsv1.2
done

2020-04-01 13:39 UTC, dermot-hardy requested changes
Update release notes and version number to reflect that this is a breaking change.

2020-04-01 13:39 UTC, dermot-hardy commented on src/main/docker/disableWeakTlsAlgorithms.patch
> +#Cipher found for TLSv1.1 in https://tools.ietf.org/html/rfc4346#page-53
Remove this line comment

2020-04-01 13:39 UTC, dermot-hardy commented on src/main/docker/disableWeakTlsAlgorithms.patch
> +#Cipher found for TLSv1.2 in https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29
Remove this line comment

2020-04-01 13:39 UTC, dermot-hardy commented on src/main/docker/disableWeakTlsAlgorithms.patch
> +# Cipher found for TLSv1.2 in https://tools.ietf.org/html/rfc5246
Remove this line comment

2020-04-01 13:39 UTC, dermot-hardy commented on src/main/docker/disableWeakTlsAlgorithms.patch
> ++    TLS_DH_anon_WITH_AES_256_CBC_SHA256
There are a lot of ciphers being listed here.  Could a wildcard be safely used?

2020-04-02 19:53 UTC, dermot-hardy approved these changes

2020-04-03 09:16 UTC, merged

2020-04-03 09:17 UTC, andyreidz commented
It looks like Dermot wanted Rob to review this.

![image](https://user-images.githubusercontent.com/18459684/78344448-4e732500-7594-11ea-9dda-631d83370bad.png)

2020-04-03 16:52 UTC, rob-duewer reviewed
See comments left on https://github.com/CAFapi/opensuse-java8-images/pull/14.

But there are a couple differences with j11 vs. j8

You need to still permit the intermediate list of ciphers (so 3 for TLS 1.3, the other safe 8 for TLS 1.2 (assuming J11 supports chaha stream cipher, I haven't looked) as long as we have any images anchored to j8.  Only after we have moved every one of our ms's to java11, should we move to excluding **everything** but the 3 current safe "modern" TLS 1.3 ciphers.  Until then, enforce the moderate safety list.

Between https://docs.oracle.com/en/java/javase/11/security/oracle-providers.html#GUID-7093246A-31A3-4304-AC5F-5FB6400405E2 and https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#jsse-cipher-suite-names, you should be able to suss out what the approropate exclusion list (explicit and shortcut) should be for our j11 use.